app:
  prefix: '/graphql'
  port: 3000
  referrerPolicy: false
  contentSecurityPolicy: false

jwt:
  secret: 'd2d95aebfe77c50b4f2188f7e774ae41f3c3188609d173f7a59a2112fa6e31ac'
  expiresIn: '6h'

apollo:
  key: service:farmaco-graphql-51ak3d:eyCOxLniIshEQrOp0xyQKQ

gateway:
  debug: true
  serviceHealthCheck: false

auth:
  url: 'localhost:3005'
